
on: 
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 
      

    steps:
      - name: 'Test Github'
        run: pwd
      - name: 'Test printing'
        run: echo ibrahim
